### ISSUE TITLE
[FEAT] 서브 도메인 자동 생성 구축

### ISSUE THREAD

**Issue by yummygyudon** [palm-springs/PalmSpringsServer#123]
## Description 📝
각 팀에서 블로그 생성시,
생성 페이지에서 입력한 블로그 이름(영문)으로 서브 도메인 자동 생성 시키는 기능

## To-Do ☑️
> _To-Do 변동 및 추가 가능_
- [x] Route 53 호스트 등록
  - [x] 서브 도메인 URL 패턴 등록 
  - [x] HTTPS 적용을 위한 SSL 인증서 발급
  - [x] Load balancer 리스너 추가
  - [x] HTTP 프로토콜 HTTPS로 리다이렉트
  - [x] Domain과 Route 53 LB 연결
- [ ] Lambda 로 작업 자동화
  - [ ] 트리거 등록 

## Reference 📚
- [https://2donny-world.tistory.com/15](https://2donny-world.tistory.com/15)
- [https://sjparkk-dev1og.tistory.com/229](https://sjparkk-dev1og.tistory.com/229)

**Comment by yummygyudon** [comment]
구축 완료 (with. @Geun-Oh )
