### ISSUE TITLE
[REFACTOR] API 구조 리팩토링 및 v2 구축 

### ISSUE THREAD

**Issue by yummygyudon** [palm-springs/PalmSpringsServer#124]
## Description 📝
기존 API 내 Controller에서 외부에서 보여지는 View의 정보를 반환하는 메서드와
Dashboard에서 생성, 수정, 삭제 등에 대한 메서드가 혼재되어 있어
가독성 및 관리 용이성이 떨어졌다.

그에 대해 폴더링 개편 및 API URL pattern 수정을 통해
가독성과 관리 용이성을 개선하고자 한다.

## To-Do ☑️
- [ ] main 브랜치에서 v2 develop 브랜치 생성 및 이관
- [ ] 폴더링 개편
  - [ ] Dashboard(PalmSpring 도메인) / BlogView(외부 각 도메인의 블로그 뷰) / System(애플리케이션에서의 전역적 개념) 로 1차 도메인 분리
- [ ] Api mapping path 수정
  - [ ] Dashboard API : `/api/v2/dashboard/...`
  - [ ] Blog View API : `/api/v2/view/...`
- [ ] READMME.md 반영
