### ISSUE TITLE
[FEAT] User Info Update

### ISSUE THREAD

**Issue by yummygyudon** [palm-springs/PalmSpringsServer#185]
## Description 📝
User Domain - `RegisterUser` & `TeamMember` 정보 변경에 대한
Update 기능 구현

## To-Do ☑️
- [ ] `RegisterUser` Update
  - [ ] 변경이 가능한 값만 수정 가능 :: `name` / `thumbnail`
  - [ ] 변경 이전에 Team에 온보딩했을 때, 기본값으로 들어갔던 변경 이전 기존 계정명에 대해서는 변동 없음!!
- [ ] `TeamMember` Update
  - [ ]  변경이 가능한 값만 수정 가능 :: `nickname` / `url` / `description` / `thumbnail` / `job` 
- [ ] 블로그 생성 시, `소유자` 또한 url을 정할 수 있도록(**Required**) 온보딩 Flow에 추가해야 함 ( 기획 & 디자인 측에 전달 )
  - [ ] 온보딩 Flow 시, 이름을 적지 않은 경우, 가입된 계정 이름으로 적용됨을 사용자에게 전달해야 함 ( 기획 & 디자인 측에 전달 )
- [ ] 해당 API 호출 및 작업 완료 응답 받았을 경우, 해당 페이지 Refresh 할 수 있도록 하기 ( 클라이언트 측에 전달 )
