### ISSUE TITLE
[FIX] TeamMember Entity - URL 값 자동생성 규칙 반영 

### ISSUE THREAD

**Issue by yummygyudon** [palm-springs/PalmSpringsServer#191]
## Description 📝
User Domain 생성 규칙 반영

## To-Do ☑️
- [x] 초대 수락하기 Flow가 없을 경우, TeamMember  고유 URL에 랜덤값 UUID 혹은 해시값으로 자동 생성
  - [x]  `url` 필드 `not null` & `unique` 속성 추가
  - [x] 생성 시, 값 자동생성 시켜주는 로직 구현 
- [x] RegisterUser 내 isActive 필드 수정
  - [x] `defaultValue` = `ACTIVE`(`Boolean.TRUE`) 로 변경
