### ISSUE TITLE
[FEAT] HTTP File 활용으로 API Test 간편화

### ISSUE THREAD

**Issue by yummygyudon** [palm-springs/PalmSpringsServer#200]
## Description 📝
HTTP File 을 활용하여
Authorization Token 등을 환경변수로 관리하고
Intellij 내에서 즉각적으로 API 테스트를 해볼 수 있도록 하며
외부 API 호출까지 손쉽게 활용할 수 있도록 합니다.

## To-Do ☑️
- [x] 관련 문서 작성 후 공유
- [x] HTTP 파일 관리 정책 및 패키징 정책 수립
- [x] 각 도메인 Controller 당 1개의 HTTP 파일로 관리
