### ISSUE TITLE
[FEAT] 메타 데이터 받기 구현

### ISSUE THREAD

**Issue by jinchiim** [palm-springs/PalmSpringsServer#206]
## Description 📝

메타 데이터 받기 구현

## To-Do ☑️
- [ ] 메타데이터 필드 추가
- [ ] 블로그 생성시 메타데이터 필드에도 같은 값 추가하는 로직 추가
- [ ] 수정 시 메타데이터 값도 받도록 추가
