### ISSUE TITLE
[REFACTOR] 권한 관리 개선 (ref. Spring Security)

### ISSUE THREAD

**Issue by yummygyudon** [palm-springs/PalmSpringsServer#208]
## Description 📝
Spring Security와 같이 Authorites 도메인을 별도로 생성하여 관리
→ 한 유저가 여러 개의 권한 객체를 가질 수 있음

## To-Do ☑️
- [ ] Authorites/Roles 도메인을 별도로 생성
  - [ ] Authorites/Roles 은 Eager Loading 
  - [ ] contains 검사의 책임을 User 도메인에 위임
- [ ]Interceptor 수정
  - [ ] 위임된 검사 방식 반영
  - [ ] `targetRoles` → `minPrivilege` : 최소 ~~ 이상으로

## Reference 📚
[Spring Security Docs](https://docs.spring.io/spring-security/reference/)
