### ISSUE TITLE
[FEAT]  구독 및 뉴스레터 발송 기능 구현

### ISSUE THREAD

**Issue by jinchiim** [palm-springs/PalmSpringsServer#210]
## Description 📝

구독 및 뉴스레터 발송 기능 구현

## To-Do ☑️
- [ ] 구독자 데이터베이스 추가 생성
- [ ] SES AWS 허가 메일 전송
- [ ] SES 메일 발송 기능 구현 => 확장성 좋도록 많은 연구 필요, 레퍼런스 많이 찾아볼 것
- [ ] 실제 발송 테스트 및 시간 체크 필요(초대도 해당 기능으로 해야하기 때문)
