### ISSUE TITLE
[FEAT] NewsLetter & Invite Mail 동적 템플릿 로드 및 발송 기능

### ISSUE THREAD

**Issue by yummygyudon** [palm-springs/PalmSpringsServer#218]
## Description 📝
설명을 작성해주세요

## To-Do ☑️
- [ ] 동적 템플릿에서 사용하는 변수들과 Mapping 될 데이터를 담은 DTO 구현
- [ ] AWS SES에 템플릿 6가지 등록
  - [ ] 뉴스레터
    - [ ] No 썸네일 & No 블로그 로고
    - [ ] No 썸네일
    - [ ] No 블로그 로고
    - [ ] (일반)
  - [ ] 초대메일
    - [ ] No 블로그 로고
    - [ ] (일반)  

- [ ] 값 유무에 따른 템플릿 load 분기 처리
  - [ ] 뉴스레터
    - [ ] No 썸네일 & No 블로그 로고
    - [ ] No 썸네일
    - [ ] No 블로그 로고
    - [ ] (일반)
  - [ ] 초대메일
    - [ ] No 블로그 로고
    - [ ] (일반)
