### ISSUE TITLE
[REFACTOR] 예외 반환 관리

### ISSUE THREAD

**Issue by yummygyudon** [palm-springs/PalmSpringsServer#225]
## Description 📝
우선 클라이언트 측에서 Response Status와 Body 내부의 `code` 라는 데이터 필드 값이 일치하지 않아
이전부터 혼동 이슈가 발생하고 있었습니다..!!

메인 피쳐가 아닐뿐더러 이미 클라이언트 측에서도 `code`라는 데이터 값을 기반으로 로직 처리를 하긴 했으나
이는 너무 건강치 않은 불안정한 애플리케이션이 될 문제이고
반환되는 예외 Response 를 우리도 예측을 못한다는 것은 어불성설이라고 생각되어
묵혀놨던 ControllerAdvice 를 다시 꺼내 활용해볼 시간이 온 것 같습니다..!!

## To-Do ☑️
- [ ] `@ControllerAdvice` & `@ExceptionHandler` 활용
  - [ ] 도메인 별 계층화 Exception 들에 대해 Handling 하기 
- [ ] ExceptionFilter 추가 구현
  - [ ] Filter Chain에서의 예외는 ControllerAdvice의 ExceptionHandler 에서 처리가 불가능
- [ ] 도메인별로 계층화 시켜놓은 Exception 기반으로 관리하며 따로 처리할 것이 있으면 처리 로직 추가 (ex. Body 내부 `data = null` 의 모습을 개선하는 등)
