### ISSUE TITLE
[FEAT] 이메일 발신자 정보 설정 및 템플릿 제목 변경

### ISSUE THREAD

**Issue by yummygyudon** [palm-springs/PalmSpringsServer#226]
## Description 📝
이메일로 발신자 이름이 설정되는 부분을 명시적인 이름으로 바꾸고
템플릿 제목 또한 기획-디자인과 논의 후 변경

## To-Do ☑️
- [ ] 이메일 발신자 정보
  - [ ] 발신자 이름
  - [ ] 발신자 프로필(썸네일)
  - [ ] 발신자 이메일 정책 
- [ ] 템플릿 제목
  - [ ] 초대 invite 템플릿
  - [ ] 뉴스레터 newsletter 템플릿
