### ISSUE TITLE
[FEAT] 최초 대시보드 유저정보 로딩 API

### ISSUE THREAD

**Issue by yummygyudon** [palm-springs/PalmSpringsServer#69]
## Description 📝
블로그 생성 직후 혹은 정석적인 플로우로 접속했을 때, 최초로 랜더링되는 대시보드 화면에서
좌측 사이드 바에 로딩 되는  기본 유저 정보 및 소속 블로그 드롭다운 리스트 관련 정보 제공 API 입니다. 

## To-Do ☑️
- [x] 소속 블로그가 있을 경우와 소속 블로그가 없을 경우 분류
- [x] 소속 블로그가 있을 경우, 드롭 다운에서 블로그 리스트업 정책 구현
  - [x] (1차 정책) 소속 블로그를 리스트로 가지고 있다고 하면 첫 번째 요소를 기본 값으로 설정
- [x] 하단 접속 유저 기본 정보
  - [x] 이름
  - [x] 이메일
  - [x] 썸네일   

## Reference 📚
<img src="https://github.com/palm-springs/PalmSpringsServer/assets/86935274/85b8348b-348e-4349-b295-77b51d167e08" height="850px" width ="250px"/>
