### ISSUE TITLE
[FEAT] 상세 유저 정보 조회 API

### ISSUE THREAD

**Issue by yummygyudon** [palm-springs/PalmSpringsServer#71]
## Description 📝
외부에서 보여지는 블로그에서의 유저 상세 정보가 아닌
Dashboard 내에서 유저 정보 수정 기능까지 포함하고 있는 Dashboard 용 유저 정보 페이지에 보여질 데이터 조회 API 입니다.

## To-Do ☑️
- [x] 유저정보
  - [x] RegisterUser ID : `팜스프링 탈퇴` 기능을 위해서 필요하다고 생각했습니다. 
  - [x] TeamMember ID : `블로그에서 나가기` 기능을 위해서 필요하다고 생각했습니다.
  - [x] 썸네일
  - [x] 닉네임(블로그 내 ID)
  - [x] 한 줄 소개(`description`)
  - [x] 직책

## Reference 📚
![image](https://github.com/palm-springs/PalmSpringsServer/assets/86935274/e120f015-3b61-4199-87f9-99d972f99567)
