### ISSUE TITLE
[REFACTOR] User 도메인 내 예외 처리를 위한 Error 관리

### ISSUE THREAD

**Issue by yummygyudon** [palm-springs/PalmSpringsServer#75]
## Description 📝
- 체계적인 에러 처리 및 예외 처리 관리
- 코드 가독성 개선

## To-Do ☑️
- [x] Jwt 관련 예외 처리
  - [x] JwtAuthorizationFilter 내에서 예외별 처리 방식 구체화 
- [x] User 도메인 관련 예외 처리
