### ISSUE TITLE
[REFACTOR] QA - User 도메인 내 발생 예외 및 에러에 대한 상세화 및 구체화 

### ISSUE THREAD

**Issue by yummygyudon** [palm-springs/PalmSpringsServer#96]
## Description 📝
QA 시 발생할 다양한 예외 상황에 최대한 맞추어
정확한 예외 발생 사항에 대해 Response를 해줄 수 있도록 합니다.

## To-Do ☑️
- [ ] Authenticate 관련 UserToken Error & Exception
- [ ] Authenticate 관련 서비스 로직에 `throw` & `try ~ catch ~ ` 철저하게 처리
- [ ] User 도메인 관련 User Error & Exception
- [ ] User 관련 서비스 로직에 `throw` & `try ~ catch ~ ` 철저하게 처리
