### ISSUE TITLE
[FEAT] 외부에서 GET 할 수 있는 아티클 작성자(팀 멤버) 상세 정보 조회 API

### ISSUE THREAD

**Issue by yummygyudon** [palm-springs/PalmSpringsServer#97]
## Description 📝
Dashboard에서가 아닌 
외부 고객사(팀) 도메인 내에서 GET 할 수 있는 아티클 작성자(팀 멤버)에 대한 상세 정보 조회 API

## To-Do ☑️
- [x] View에서 확인 가능한 정보들의 형식에 맞춘 DTO 처리
  - [x] 썸네일(TeamMember - `thumnail`)
  - [x] 이름(`nickname`)
  - [x] 직책(`job`)
  - [x] 한 줄 소개 (`discription`)
  - [x] 작성한 아티클 (`List<Article>`) : _Nullable_
    - [x] 제목 
    - [x] 아티클 썸네일 : _Nullable_
    - [x] 아티클 한 줄 소개
    - [x] 아티클 카테고리
    - [x] 작성자
    - [x] 작성 일자

## Reference 📚
![image](https://github.com/palm-springs/PalmSpringsServer/assets/86935274/3da2f09d-e1c1-46d8-b66c-c97c094c9255)
![image](https://github.com/palm-springs/PalmSpringsServer/assets/86935274/f96288c6-5693-4985-a2fa-794797fea598)
